### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by Magagar** [CINPLA/tracking-plugin#13]
Hi, I'm trying to make the tracking-plugin work, but I have 2 problems at the moment that I was hoping you could help me with? 

In the tracking port, it looks like I can't select any tracking source in the recording box to save the tracking data (see image 1 attached). The second problem is that in the tracking visualiser sometimes I can only see one of the tracking sources, sometimes both and sometimes none (this seems to change each time I open the Open Ephys GUI - images 2 and 3).

Thanks in advance for your help.

![tracking port](https://user-images.githubusercontent.com/52216054/60122784-d9113300-977d-11e9-88c0-3032ca38b2dc.JPG)
![plot](https://user-images.githubusercontent.com/52216054/60122794-ddd5e700-977d-11e9-9887-d90d15d3e2e2.JPG)
![plot_2](https://user-images.githubusercontent.com/52216054/60123286-01e5f800-977f-11e9-8507-e66e7dfb6876.JPG)

**Comment by alejoe91** [comment]
Hi @Magagar. 
If you use the binary format, sources tracking data are saved automatically. Saving binary info is not supported in open ephys format.
Love
Regarding the second problem, there is a bug with the latest GUI when you reload the tracking port. Basically only one source gets captured. I'll try to fix this soon, but in the meanwhile you can just remove the sources from the tracking port and re-add them. This should work
