### ISSUE TITLE
Update to new cmake build system

### ISSUE THREAD

**Issue by alejoe91** [CINPLA/tracking-plugin#14]

**Comment by alejoe91** [comment]
https://github.com/CINPLA/tracking-plugin/tree/update

**Comment by markschatza** [comment]
Hi @alejoe91 

Looks like the tracking plugin won't be as easy to convert over. Not sure exactly how to link to the oscpack library that you are using. The bottom of the readme talks about including external libraries. https://github.com/open-ephys-plugins/OEPlugin.

I can try to help if you attempt to tackle this yourself, but you'd probably get better help by reaching out to the OE folks.

**Comment by alejoe91** [comment]
I was able to build using this trick: https://github.com/CINPLA/tracking-plugin/blob/update/Tracking/CMakeLists.txt

Thanks for looking into it :) I'll try to merge these changes with the OEPlugin CMakeList format

**Comment by alejoe91** [comment]
@markschatza 

https://github.com/CINPLA/tracking-plugin/pull/15 works on my side. Thanks for pointing to the right resources. :)

**Comment by alejoe91** [comment]
Could I ask you to test the build on Windows? I had to add a link to two windows-spesicif libraries and it should compile with no problem on windows too
