### ISSUE TITLE
sync recording video and ephys

### ISSUE THREAD

**Issue by ChangQing-SH** [CINPLA/tracking-plugin#18]
Hi,

the plugin works well, and it is really awesome, but I am curious how can I sync record the video and ephys? 
currently, capture the video on Bonsai, and save the video with videowriter, and at the same time with your bonsai workflow, it sends tracking data to openephyGUI,  but how to sync the video and ephys?
My best,
Jon

**Comment by alejoe91** [comment]
HI @ChangQing-SH 

Sorry I see this only now!! As I suggested here https://github.com/CINPLA/tracking-plugin/issues/19, maybe the best option is to sent timestamps from Bonsai via OSC as well, and save them in the binary packet along with x,y,width and height. This way, you should be able to access the timestamps given by Bonsai. Let's discuss in the other issue, closing this one
