### ISSUE TITLE
Data read from tracking plugin output via `pyopenephys` 

### ISSUE THREAD

**Issue by lillysanchez** [CINPLA/tracking-plugin#21]
Devs,
I'm seeing unexpected output when using your `pyopenephys` package to read the output of my tracking test using your plugin and bonsai with a Basler camera. The output of the plugin in open ephys looks reasonable enough moving a red led back and forth along a linear maze.
![Capture](https://user-images.githubusercontent.com/101027233/177693271-debe523d-090e-4d6c-bfa7-64869ee484b1.PNG)
 
However, the binary (`npy`) recording output from open ephys has 16 columns, not the 8 I was expecting (4 from red and 4 from green channel, although the green channel is not in use right now). The `pyopenephys` script states the 1st and 2nd column should be the *x* and *y* coordinates, but these values do not make sense. It is actually the 3rd column that seems to output *x*, but no corresponding *y* channel is reasonable. Even the *x* channel (in `data[:,2]`) contains very incomplete data compared to that shown in the screenshot above. The incomplete data from the third column is shown in the attached plot: 
![Figure_1](https://user-images.githubusercontent.com/101027233/177693930-ec3bc0a7-b54b-4e7f-acab-f8898b9e4e4f.png)

Can you tell me if that kind of data is expected, despite the clean look of the tracking plugin output in open ephys. How can I get the data directly from the plot in open ephys rather than the record node?

**Comment by alejoe91** [comment]
Hi @lillysanchez 

What version of the open ephys GUI are you using? 
Are you using `pyopenephys` to read the data or are you loading the `npy` directly with `np.load`?
In the latter case, you need to unpack the 16 bytes into 4 floats, corresponding to `x`, `y`, `width` and `height` for each sample.

You can see you this is done in pyopenephys here: https://github.com/CINPLA/pyopenephys/blob/42ba4534be7576ae82abec1364b71dd091348ecb/pyopenephys/core.py#L745-L749

**Comment by lillysanchez** [comment]
Thanks for replying. I was using the CINPLA python data reader (`pyopenephys`), but it doesn't handle the newer OpenEphys format with multiple record nodes. 

Instead, I was able to read the data using numpy's binary reader. 

```python
da = np.load(‘data_array.npy’)
x = np.frombuffer(da.flatten(), dtype=np.single)[::4]
y = np.frombuffer(da.flatten(), dtype=np.single)[1::4]
width = np.frombuffer(da.flatten(), dtype=np.single)[2::4]
height = np.frombuffer(da.flatten(), dtype=np.single)[3::4]
```

The last four lines are converting the byte buffer into float values, then extracting the x and y position, as well as the image width and height values (which are constant).
