### ISSUE TITLE
initialization not compatible with VS2013

### ISSUE THREAD

**Issue by lepmik** [CINPLA/tracking-plugin#7]
https://github.com/CINPLA/tracking-plugin/blob/157f9368cf2f40abed00301ebaab9fe3bf4e4c69/Tracking/TrackingNodeEditor.h#L56

e.g. set the array elements in the constructor

**Comment by lepmik** [comment]
https://github.com/CINPLA/tracking-plugin/blob/157f9368cf2f40abed00301ebaab9fe3bf4e4c69/Tracking/TrackingVisualizerCanvas.h#L96

Same problem here

**Comment by alejoe91** [comment]
Turns out the msvc compiler doesn't like arrays of Juce String.
I used Juce::Array instead and it seems to be solving basically all the problems.
a1899d0612f0f3637b68ba80700ea7d3343b52af

**Comment by alejoe91** [comment]
@lepmik  can you try to compile and run the latest commit on the VS2013 branch?
It seems to work fine on the PC here :)
